### ISSUE TITLE
`Cannot find module '../node_modules/comlink/dist/esm/comlink.mjs'` in build-3

### ISSUE THREAD

**Issue by jamesgpearce** [tomayac/sqlite-wasm#24]
When trying to simply:

`import sqlite3InitModule from '@sqlite.org/sqlite-wasm';`

I get:

`Cannot find module '../node_modules/comlink/dist/esm/comlink.mjs' from 'node_modules/@sqlite.org/sqlite-wasm/src/sqlite-client.mjs'`

Maybe a src file shouldn't be in the prod distro (from index.mjs: `export * from './src/sqlite-client.mjs';`).

This worked fine with build 2.

**Comment by tomayac** [comment]
Duh, this was introduced with #22. Working on a fix now.

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/sqlite-wasm/commit/aa83116bfcb807a8728508cc0b8c3f65d2ae44fa.

**Comment by jamesgpearce** [comment]
Awesome. Thanks!
